export const JWTOKEN_COOKIE_NAME = 'jwTokenCookie'
export const BACKEND_API_URL = 'http://localhost:8090'
export const AUTHORIZATION_HEADER_NAME = 'authorization'
export const JWTOKEN_PREFIX = 'Bearer '
export const LOGGED_USERNAME_COOKIE_NAME = 'loggedUsername'
